pipeline {
    agent any
    
    stages {
        stage('git checkout') {
            steps {
                 git 'https://github.com/poojadevops1/simple-java-maven-app' 
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Execute') {
            steps {
                // Execute the generated JAR file
                sh 'java -jar target/my-app-1.0-SNAPSHOT.jar'
            }
        }
    }
}
